"""French → English common-name lookup for Paris street-tree species.

The `les-arbres` dataset only records a French common name (`libellefrancais`,
e.g. *Platane*, *Marronnier*). The front end wants the species in English too, so
this module maps each distinct French name to its English common name.

The map is keyed on the dataset's French names. A few values carry CSV-escaping
artefacts (doubled quotes) or cultivar suffixes; `english_name()` normalises those
before lookup. Anything genuinely unknown falls back to the French name unchanged
(honest — better than a wrong guess), so the English field is always populated.
"""

from __future__ import annotations

import re

# French common name → English common name. Ordered roughly by Paris frequency.
# Where no settled English common name exists, the scientific/genus name is used
# (valid in English usage); truly obscure single specimens fall back to French.
_FR_TO_EN: dict[str, str] = {
    'Platane': 'Plane tree',
    'Marronnier': 'Horse chestnut',
    'Tilleul': 'Linden',
    'Erable': 'Maple',
    'Sophora': 'Pagoda tree',
    'Chêne': 'Oak',
    'Pin': 'Pine',
    'Micocoulier': 'Hackberry',
    'Frêne': 'Ash',
    'Cerisier à fleurs': 'Flowering cherry',
    'Poirier à fleurs': 'Flowering pear',
    'Charme': 'Hornbeam',
    'Noisetier de Byzance': 'Turkish hazel',
    'If': 'Yew',
    'Peuplier': 'Poplar',
    'Robinier': 'Black locust',
    'Orme': 'Elm',
    'Bouleau': 'Birch',
    'Hêtre': 'Beech',
    'Magnolia': 'Magnolia',
    'Fevier': 'Honey locust',
    'Paulownia': 'Foxglove tree',
    'Arbre de Judée': 'Judas tree',
    'Pommier à fruits': 'Apple',
    'Pommier à fleurs': 'Flowering crabapple',
    'Charme-Houblon': 'Hop hornbeam',
    'Arbre aux quarante écus': 'Ginkgo',
    'Merisier': 'Wild cherry',
    'Frêne à fleurs': 'Manna ash',
    'Cèdre': 'Cedar',
    'Lilas des indes': 'Crape myrtle',
    'Savonnier': 'Goldenrain tree',
    'Mûrier': 'Mulberry',
    'Poirier à fruits': 'Pear',
    'Noyer': 'Walnut',
    'Cedrele': 'Chinese mahogany',
    'Orme de Sibérie': 'Siberian elm',
    'Prunier à fleurs': 'Flowering plum',
    'Copalme': 'Sweetgum',
    'Cerisier à grappes': 'Bird cherry',
    'Ailante': 'Tree of heaven',
    'Tulipier': 'Tulip tree',
    'Amélanchier': 'Serviceberry',
    'Aulne': 'Alder',
    'Cyprès': 'Cypress',
    'Pterocarya': 'Wingnut',
    'Prunus n. sp.': 'Cherry (Prunus)',
    'Cornouiller': 'Dogwood',
    'Catalpa': 'Catalpa',
    'Parrotie de Perse - Arbre de fer': 'Persian ironwood',
    'Non spécifié': 'Unspecified',
    'Saule': 'Willow',
    'Thuya': 'Arborvitae',
    'Houx': 'Holly',
    'Arbre à soie': 'Silk tree',
    'Pommier': 'Apple',
    'Chicot du Canada': 'Kentucky coffeetree',
    'Troene': 'Privet',
    'Aubépine': 'Hawthorn',
    'Palmier': 'Palm',
    'Faux-cyprès': 'False cypress',
    'Sorbier': 'Rowan',
    'Epicéa': 'Spruce',
    'Troëne': 'Privet',
    'Châtaignier': 'Sweet chestnut',
    'Aubepine': 'Hawthorn',
    'Arbre à caramel': 'Katsura tree',
    'Olivier': 'Olive',
    'Aria edulis': 'Whitebeam',
    'Alisier': 'Wild service tree',
    'Parrotie de Perse': 'Persian ironwood',
    'Figuier': 'Fig',
    'Noisetier': 'Hazel',
    'Buis': 'Boxwood',
    'Plaqueminier': 'Persimmon',
    'Prunier à fruits': 'Plum',
    'Sapin': 'Fir',
    'Sureau': 'Elder',
    'Eleagnus - Chalef': 'Oleaster',
    'Metaséquoia': 'Dawn redwood',
    'Sequoia': 'Sequoia',
    'Lilas de Perse': 'Persian lilac',
    'Poirier': 'Pear',
    'Laurier du Portugal': 'Portugal laurel',
    'Cognassier': 'Quince',
    'Arbousier': 'Strawberry tree',
    'Abricotier': 'Apricot',
    'Amandier': 'Almond',
    'Arbre à miel': 'Bee bee tree',
    'Eucalyptus': 'Eucalyptus',
    'Pêcher': 'Peach',
    'Photinia': 'Photinia',
    'Chitalpa': 'Chitalpa',
    'Oranger des Osages': 'Osage orange',
    'Libocèdre': 'Incense cedar',
    'Virgilier': 'Yellowwood',
    'Fontanesia': 'Fontanesia',
    'Filaire': 'Mock privet',
    'Néflier commun': 'Medlar',
    'Cerisier à fruits': 'Cherry',
    'Néflier': 'Medlar',
    'Cytise': 'Laburnum',
    'Laurier-Cerise': 'Cherry laurel',
    'Clerodendron': 'Glorybower',
    'Cabrillet': 'Cabrillet cherry',
    'Sumac': 'Sumac',
    'Cerisier à fleurs, cerisier griotte': 'Flowering / sour cherry',
    'Laurier sauce': 'Bay laurel',
    'Mélèze': 'Larch',
    'Céphalotaxe': 'Plum yew',
    'Prunus Fleur n. sp.': 'Flowering cherry (Prunus)',
    'Genévrier': 'Juniper',
    'Amelanchier': 'Serviceberry',
    'Gainier': 'Redbud',
    'Phellodendron': 'Cork tree',
    'Araucaria': 'Monkey puzzle',
    'Cyprès Chauve': 'Bald cypress',
    'Tamaris': 'Tamarisk',
    'Arbre aux mouchoirs': 'Handkerchief tree',
    'Caryer': 'Hickory',
    'Nothofagus': 'Southern beech',
    'Tupélo': 'Tupelo',
    'Althéa': 'Rose of Sharon',
    'Cormier': 'Service tree',
    'Alangium': 'Alangium',
    'Poivrier': 'Pepper tree',
    'Orme de Samarie': 'Hop tree',
    'Fusain': 'Spindle tree',
    'Arbre à perruque': 'Smoke tree',
    'Arbre à Gutta-Percha': 'Hardy rubber tree',
    'Laurier des Iroquois': 'Sassafras',
    'Cryptomeria': 'Japanese cedar',
    'Sterculier': 'Sterculia',
    'Heptacodion de Chine': 'Seven-son flower',
    'Grenadier': 'Pomegranate',
    'Laurier du caucase': 'Caucasian laurel',
    'Sycoparrotia': 'Sycoparrotia',
    'Prunus Fruit n. sp.': 'Plum/cherry (Prunus)',
    'Camphrier': 'Camphor tree',
    'Argousier': 'Sea buckthorn',
    'Sapin Douglas': 'Douglas fir',
    'Parrotie': 'Persian ironwood',
    'Cunninghamia': 'Chinese fir',
    'Chèvrefeuille': 'Honeysuckle',
    'Prunellier': 'Blackthorn',
    'Cotoneaster': 'Cotoneaster',
    'Muscadier': 'Nutmeg tree',
    'Tsuga': 'Hemlock',
    'Halesia': 'Silverbell',
    'Chimonanthe': 'Wintersweet',
    'Angélique': 'Angelica tree',
    'Viorne': 'Viburnum',
    'Staphylier': 'Bladdernut',
    'Pterostyrax': 'Epaulette tree',
    'Rhododendron': 'Rhododendron',
    'Pistachier': 'Pistachio',
    'Raisinier': 'Japanese raisin tree',
    'Abricotier fruit': 'Apricot',
    'Lilas': 'Lilac',
    'Fremontia': 'Flannelbush',
    'Poliothyrsis': 'Pearlbloom tree',
    'Hiba': 'Hiba arborvitae',
    'Citronnier': 'Lemon',
    'Ginkgo': 'Ginkgo',
    'Olivier odorant': 'Sweet olive',
    'Sycopsis': 'Sycopsis',
    'Paliurus': "Christ's thorn",
    'Laurier': 'Laurel',
    'Buddleja': 'Butterfly bush',
    'Faux dattier': 'False date palm',
    'Podocarpus': 'Podocarpus',
    'Bischofia': 'Bishop wood',
    'Nerprun': 'Buckthorn',
    'Caraganier': 'Pea tree',
    'Arbre à savon': 'Soapberry',
    'Ficus': 'Fig',
    'Erable de Freeman Armstrong': 'Freeman maple',
    'Idesia': 'Iigiri tree',
    'Asiminier': 'Pawpaw',
    'Maackie': 'Maackia',
    'Callistemon': 'Bottlebrush',
    'Ostryer': 'Hop hornbeam',
    'Gainier de Chine Shirobana': 'Chinese redbud',
    'Caroubier': 'Carob',
    'Ormeau épineux': 'Thorn elm',
    'Exochorde': 'Pearlbush',
    'Plagianthe': 'Ribbonwood',
    'Arbre à soie Summer Chocolate': 'Silk tree',
    'Bourdaine': 'Alder buckthorn',
    'Aubépine hybride': 'Hybrid hawthorn',
    'Myrte du Chili': 'Chilean myrtle',
    'Taiwania': 'Taiwania',
    'Genêt': 'Broom',
    'Kalopanax': 'Castor aralia',
    'Styrax': 'Snowbell',
    'Cordyline': 'Cabbage tree',
    'Platycarya': 'Platycarya',
    'Aronie': 'Chokeberry',
    'Aliboufier': 'Storax',
    'Laurier de Californie': 'California laurel',
    'Daphniphyllum': 'Daphniphyllum',
    'Kétéleeria': 'Keteleeria',
    'Caragana': 'Pea tree',
    'Amandier à fleurs': 'Flowering almond',
    'Kaki': 'Persimmon',
    'Cudranier': 'Che',
    'Goyavier': 'Guava',
    'Brucea javanica': 'Java brucea',
    'Laurier des Açores': 'Azores laurel',
    'Arbre aux perles': 'Pearl tree',
    'Lithocarpus': 'Stone oak',
    'Faux pistachier': 'False pistachio',
    'Sophora flavescens': 'Shrubby sophora',
    'Styphnolobium microphylla': 'Pagoda tree',
    "Cyprès de l'Arizona": 'Arizona cypress',
    'Glycine': 'Wisteria',
    'Noisetier fruit': 'Hazelnut',
    'Papayer': 'Papaya',
    'Euscaphis': 'Korean sweetheart tree',
    'Oranger de Chine': 'Sweet orange',
    'Lindera': 'Spicebush',
    'Stachyurus': 'Stachyurus',
    'Pteroceltis': 'Blue sandalwood',
    'Faux-poivrier': 'Pepper tree',
    'Garrya': 'Silk tassel',
    'Parrotiopsis': 'Parrotiopsis',
    'Chionanthe': 'Fringe tree',
    'Castanopsis': 'Chinquapin',
    'Hamamélis': 'Witch hazel',
    'Seringas': 'Mock orange',
    'Abelia': 'Abelia',
    'Mimosa': 'Mimosa',
    'Faux-cyprès': 'False cypress',
}

# Cultivar/clone suffix stripped before lookup: a SPACE-separated quoted token at
# the end (e.g. ``Aria edulis 'Magnifica'``). The leading ``\s+`` is what keeps an
# internal apostrophe — ``Cyprès de l'Arizona`` — from being mistaken for one.
_CULTIVAR_SUFFIX = re.compile(r"\s+'[^']*'$")


def _normalise(name: str) -> str:
    """Collapse CSV-escaping artefacts so a name matches a base key.

    Un-doubles quotes, drops a trailing space-separated quoted cultivar/clone token,
    and trims stray edge quotes (e.g. ``Aria edulis ''Magnifica''`` → ``Aria
    edulis``; ``Cyprès de l''Arizona''`` → ``Cyprès de l'Arizona``).
    """
    cleaned = name.replace("''", "'").strip()
    base = _CULTIVAR_SUFFIX.sub('', cleaned).strip().strip("'").strip()
    return base


def english_name(french: str) -> str:
    """Return the English common name for a French species name.

    Falls back to the (de-artefacted) French name itself when no translation is
    known, so the result is never empty for a named tree. An empty input (a tree
    with no recorded species) maps to ``''``.
    """
    if not french:
        return ''
    if french in _FR_TO_EN:
        return _FR_TO_EN[french]
    base = _normalise(french)
    return _FR_TO_EN.get(base, base)
